### ISSUE TITLE
Crash in engine causes thumbor to hang for a while.

### ISSUE THREAD

**Issue by aectann** [DomainGroupOSS/opencv-engine#1]
We need to investigate and make it 1) nor crash 2) do not hang on crashes.

Example requests causing problems are below:

`10.123.2.172 - - [24/Sep/2015:05:37:55 +1000] "GET /wyTFzqa2eo99RDYcLyM2Ri49BM8=/82x82/top/filters:no_upscale()/http:/images.domain.com.au/img/26295/contact_1255849.JPG?mod=150922-210601 HTTP/1.1" 499 0 "http://www.domain.com.au/for-sale/19-panorama-drive-doonan-qld-4562-2012074334?utm_source=domain-homepage&utm_medium=link&utm_content=position2&utm_campaign=domainhomepage_dreamhomes&utm_term=2012074334" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.123.2.172 - - [24/Sep/2015:05:50:25 +1000] "GET /BhC5siF-5pUr4IiUdv_8HvILIV0=/82x82/top/filters:no_upscale()/http:/images.domain.com.au/img/248/contact_1236067.JPG?mod=150920-051408 HTTP/1.1" 499 0 "http://www.domain.com.au/for-sale/303-14-macleay-street-potts-point-nsw-2011-2012268022?sp=6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"
10.123.1.103 - - [24/Sep/2015:06:06:36 +1000] "GET /wyTFzqa2eo99RDYcLyM2Ri49BM8=/82x82/top/filters:no_upscale()/http:/images.domain.com.au/img/26295/contact_1255849.JPG?mod=150922-210601 HTTP/1.1" 499 0 "http://www.domain.com.au/for-sale/19-panorama-drive-doonan-qld-4562-2012074334?utm_source=brisbane-times&utm_medium=link&utm_content=position2&utm_campaign=masthead_featured_listings&utm_term=2012074334" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"
10.123.1.103 - - [24/Sep/2015:06:09:40 +1000] "GET /Ygn3kfneE3rptBPvJWfq45Kx46s=/165x165/top/filters:no_upscale()/http:/images.domain.com.au/img/26295/contact_1255849.JPG?mod=150922-210601 HTTP/1.1" 499 0 "http://www.domain.com.au/for-sale/37-tallgum-avenue-doonan-qld-4562-2012251905?sp=13&utm_source=Facebook&utm_medium=editorial&utm_campaign=ON&noshow=true" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"
10.123.2.172 - - [24/Sep/2015:06:36:39 +1000] "GET /wyTFzqa2eo99RDYcLyM2Ri49BM8=/82x82/top/filters:no_upscale()/http:/images.domain.com.au/img/26295/contact_1255849.JPG?mod=150922-210601 HTTP/1.1" 499 0 "http://www.domain.com.au/for-sale/19-panorama-drive-doonan-qld-4562-2012074334?utm_source=domain-homepage&utm_medium=link&utm_content=position2&utm_campaign=domainhomepage_dreamhomes&utm_term=2012074334" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"`

**Comment by gservat** [comment]
For completeness sake, this is the error we see:

```
OpenCV Error: Unspecified error (could not find encoder for the specified extension) in imencode, file /home/ubuntu/opencv-ecd36611193c88d84fa77b069181b80d10acb858/modules/imgcodecs/src/loadsave.cpp, line 609
2015-09-24 13:13:58 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 128, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 91, in apply_filters
    exec_one_filter()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 90, in exec_one_filter
    f.run(exec_one_filter)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 201, in run
    callback()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 86, in exec_one_filter
    callback()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 126, in transform
    Transformer(self.context).transform(after_transform_cb)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 89, in transform
    self.smart_detect()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 124, in smart_detect
    self.do_image_operations()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 217, in do_image_operations
    callback = inner
  File "/usr/local/lib/python2.7/dist-packages/thumbor/context.py", line 281, in queue
    self._execute_in_foreground(operation, callback)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/context.py", line 270, in _execute_in_foreground
    callback(result)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 213, in inner
    self.done_callback()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 168, in after_transform
    self.filters_runner.apply_filters(thumbor.filters.PHASE_POST_TRANSFORM, finish_callback)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 268, in finish_request
    callback=inner,
  File "/usr/local/lib/python2.7/dist-packages/thumbor/context.py", line 281, in queue
    self._execute_in_foreground(operation, callback)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/context.py", line 269, in _execute_in_foreground
    result.set_result(operation())
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 211, in _load_results
    results = context.request.engine.read(image_extension, quality)
  File "/usr/local/lib/python2.7/dist-packages/opencv3_engine/engine.py", line 54, in read
    data = cv2.imencode(extension, self.image, options or [])[1].tostring()
```
